---
- name: Install Docker and Docker-Compose
  hosts: node
  become: true
  tasks:
   - name: install dependencies
     apt:
        name: "{{item}}"
        state: present
        update_cache: yes
     loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

   - name: Docker GPP Keys Install
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: Docker Repository Dowland
     apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

   - name: Docker Install
     apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
     loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

   - name: Docker Service Enable
     service:
        name: docker
        state: started
        enabled: yes
 
   - name: Install Docker Compose 
     get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        #mode: 755
        mode: 'a+x'
 
   - name: Create docker group
     group:
        name: "docker"
        state: present

   - name: Adding user {{ USER }} to docker group
     user:
       name: "node2"
       groups: "docker"
       append: "yes"

  # - name: Add remote "ubuntu" user to "docker" group
  #   remote_user: ubuntu
  #   user:
  #     name: "node2"
  #     group: "docker"
  #     append: yes
  #   tags:
  #     - docker

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted

  # - name: Reboot server
  #   command: /sbin/reboot